# Generated by Django 4.2.7 on 2023-12-25 05:55

import accounts.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifes', models.IntegerField(default=5, verbose_name='Жизни')),
                ('recoverytime', models.DurationField(default=datetime.timedelta(seconds=600), verbose_name='Время до восстановления жизни')),
                ('crystals', models.IntegerField(default=100, verbose_name='Кристалы')),
                ('admin', models.BooleanField(default=False, verbose_name='Права админа')),
                ('avatar', models.FileField(blank=True, upload_to='avatars', verbose_name='Аватар')),
                ('theme', models.IntegerField(default=accounts.models.get_rand_theme, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Тема')),
                ('bio', models.TextField(default=accounts.models.get_rand_bio, verbose_name='Биография')),
                ('country', models.CharField(default=accounts.models.get_rand_country, max_length=30, verbose_name='Страна')),
                ('city', models.CharField(default=accounts.models.get_rand_city, max_length=30, verbose_name='Город')),
                ('code', models.CharField(default=accounts.models.get_rand_code, max_length=6, unique=True, verbose_name='Код')),
                ('friends', models.ManyToManyField(blank=True, to='accounts.student', verbose_name='Друзья')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests_to', to='accounts.student', verbose_name='От кого')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests_from', to='accounts.student', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Запрос на дружбу',
                'verbose_name_plural': 'Запросы на дружбу',
            },
        ),
        migrations.CreateModel(
            name='FriendNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendnotification_to', to='accounts.student', verbose_name='От кого')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendnotification_from', to='accounts.student', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
